version: '3.3'
services:

  elastic-tutorial:
    image: sebczu/personal:${APPLICATION_VERSION}
    container_name: elastic-tutorial
    ports:
      - 8080:8080
    environment:
      - SPRING_ELASTICSEARCH_URIS=elastic:9200

  elastic:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: kibana:${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic
